### ISSUE TITLE
Query by Example API is set in the project as mentioned at issue #3 

### ISSUE THREAD

**Issue by theVelopr** [sweatboys/open-discogs-api#6]
We decided to use Query by example API from Spring Data R2DBC finally for the issue #3.

- The data being called with `id` from common tables should be sorted by `data_quality` as well. 
- when `?` is used, not using `id` on page request through query, the result won't search the `id`.

**Comment by state303** [comment]
Separation on queries has been made to https://github.com/sweatboys/open-discogs-api/commit/b6c508e6136895bbf3f7e253f240276e34b87d8f and probably will be an example to be developed further, unifying the query mechanism in more broad sense. So I think we can close this issue since we are already following a guideline where we use id for more detailed data, queries for more broad sense (that has paging, search feature.)
